services:
  n8n:
    image: 'docker.n8n.io/n8nio/n8n'
    restart: unless-stopped
    ports:
      - "5678:5678"  # Expose n8n directly to the internet
    environment:
      - GENERIC_TIMEZONE=Europe/Brussels
      - TZ=Europe/Brussels
      - N8N_SECURE_COOKIE=false  # Required to fix the login error over http
    volumes:
      - ./n8n_data:/home/node/.n8n
    networks:
      - app-network

  mcp-gateway:
    image: docker/mcp-gateway
    command:
      - --servers=neo4j-cypher,neo4j-memory,context7,fetch
      - --transport=streaming
      - --port=3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "3000:3000"
    networks:
      - app-network
  
  neo4j:
    image: 'neo4j:5.26'
    container_name: neo4j-mldsgraph
    restart: always
    ports:
      - "7474:7474"  
      - "7687:7687"
    environment:
      -  NEO4J_AUTH: neo4j/password
      -  NEO4JLABS_PLUGINS: '["apoc", "n10s"]'
    volumew:
      - "./neo4j-volume:/data" 


networks:
  app-network:
    driver: bridge